import ArrowLeftDown from "@/icons/arrow-left-down";
import ArrowRightUp from "@/icons/arrow-right-up";

export const sliderItems = [
  {
    circleOneClassName: "text-gray-400 dark:text-gray-600",
    circleTwoClassName: "text-blue-500",
    className: "w-20 h-20",
    strokeDasharray: "360",
    strokeDashoffset: "200",
    text: "Total Price",
    price: "500k",
    Icon: ArrowLeftDown,
  },
  {
    circleOneClassName: "text-gray-400 dark:text-gray-600",
    circleTwoClassName: "text-blue-500",
    className: "w-20 h-20",
    strokeDasharray: "360",
    strokeDashoffset: "200",
    text: "Total Price",
    price: "500k",
    Icon: ArrowLeftDown,
  },
  {
    circleOneClassName: "text-gray-400 dark:text-gray-600",
    circleTwoClassName: "text-blue-500",
    className: "w-20 h-20",
    strokeDasharray: "360",
    strokeDashoffset: "200",
    text: "Total Price",
    price: "500k",
    Icon: ArrowRightUp,
  },
  {
    circleOneClassName: "text-gray-400 dark:text-gray-600",
    circleTwoClassName: "text-blue-500",
    className: "w-20 h-20",
    strokeDasharray: "360",
    strokeDashoffset: "200",
    text: "Total Price",
    price: "500k",
    Icon: ArrowLeftDown,
  },
  {
    circleOneClassName: "text-gray-400 dark:text-gray-600",
    circleTwoClassName: "text-blue-500",
    className: "w-20 h-20",
    strokeDasharray: "360",
    strokeDashoffset: "200",
    text: "Total Price",
    price: "500k",
    Icon: ArrowRightUp,
  },
  {
    circleOneClassName: "text-gray-400 dark:text-gray-600",
    circleTwoClassName: "text-blue-500",
    className: "w-20 h-20",
    strokeDasharray: "360",
    strokeDashoffset: "200",
    text: "Total Price",
    price: "500k",
    Icon: ArrowLeftDown,
  },
  {
    circleOneClassName: "text-gray-400 dark:text-gray-600",
    circleTwoClassName: "text-blue-500",
    className: "w-20 h-20",
    strokeDasharray: "360",
    strokeDashoffset: "200",
    text: "Total Price",
    price: "500k",
    Icon: ArrowRightUp,
  },
];
